services:

  # ─────────────────────────────
  # MYSQL — Video Metadata DB
  # ─────────────────────────────
  mysql:
    image: mysql:8.0
    container_name: streamforge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streamforge_db
      MYSQL_USER: streamforge
      MYSQL_PASSWORD: streamforge
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - streamforge-network

  # ─────────────────────────────
  # ZOOKEEPER — Kafka dependency
  # ─────────────────────────────
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.4.0
#    container_name: streamforge-zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - streamforge-network
#
#  # ─────────────────────────────
#  # KAFKA — Event Streaming
#  # ─────────────────────────────
#  kafka:
#    image: confluentinc/cp-kafka:7.4.0
#    container_name: streamforge-kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#
#    networks:
#      - streamforge-network

  # ─────────────────────────────

  # REDIS
  # ─────────────────────────────
  redis:
    image: redis:7
    container_name: streamforge-redis
    ports:
      - "6379:6379"
    networks:
      - streamforge-network
    restart: unless-stopped


#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: streamforge-backend
#    depends_on:
#      - mysql
#      - kafka
#      - redis
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/streamforge_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
#      SPRING_DATASOURCE_USERNAME: streamforge
#      SPRING_DATASOURCE_PASSWORD: streamforge
#
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
#
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#
#    networks:
#      - streamforge-network

volumes:
  mysql-data:

networks:
  streamforge-network:
    driver: bridge